// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpfmfvivpywoxywbgxuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwZm1mdml2cHl3b3h5d2JneHVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTM1MDIsImV4cCI6MjA2NTkyOTUwMn0.ToySNLRlCch7oGYxFwhIivyRufVGqm0BGnS_cEk9VQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);